# Generated by Django 2.2.3 on 2019-09-18 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('SLIDER', 'SLIDER'), ('BLOG', 'BLOG')], default='product', max_length=24)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.ImageSize')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
